### ISSUE TITLE
Spherical coordinates run

### ISSUE THREAD

**Issue by miniufo** [milankl/ShallowWaters.jl#164]
Hi, this is a great model I've been searching for!  Just want to know if it can be applied to the case in spherical coordinates instead of cartesian coordinates?  I may use this to study the flow on the earth.

**Comment by milankl** [comment]
No, the cartesian coordinates are very much hardcoded and generalising it to spherical coordinates is not trivial in this model, but also in general because of the poles. If you want a shallow water model on the sphere then I recommend using [SpeedyWeather.jl](https://github.com/SpeedyWeather/SpeedyWeather.jl) where
```julia
using SpeedyWeather.jl
run_speedy(ShallowWater)
```
will solve the shallow water equation on the sphere using spherical harmonics. We are currently developing this model and the ShallowWaterModel was only a step towards the primitive equations so it has fewer features but please check it out and raise any issues if you know how you'd like to use it. The documentation is lagging behind so just ask!

**Comment by miniufo** [comment]
Yes, I see speedyweather.jl during the miniute.  That's amazing and is really what I need.  Thanks.
